### ISSUE TITLE
Customisable Shortcuts

### ISSUE THREAD

**Issue by jayadevanraja** [afichet/gthumb-openexr-extension#3]
Can we customise shortcuts for instructions? For example, while playing videos, mouse click causes toggling between Pause and Play. Can we change it to Space key instead of mouse click?

**Comment by afichet** [comment]
Hello,
This repo is about an extension for gThumb. You're probably referring to gThumb itself which I have no control over.
Regards.

**Comment by jayadevanraja** [comment]
Sir, Is not this the extension which enables gThumb to play videos?
If this is not the right page, can you please be kind enough to guide me which page will be more appropriate?

**Comment by afichet** [comment]
No it's not. It's an extension to load OpenEXR image format.
Sorry, can't help you. good luck tho
